name: ValentinesDay
version: 0.0.1
description: PPL-Assignment

author: Pranjal Paliwal <paliwal.pranjal83@gmail.com>
homepage: https://betterclever.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  csv: '3.1.2'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
